apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Compõe a base (namespace, config, secrets, ingress, postgres)
# com os módulos de aplicação (api e web).
resources:
  - base
  - modules/api
  - modules/web